# Generated by Django 3.0 on 2019-12-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attraction_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('is_landmark', models.BooleanField(default=False)),
            ],
        ),
    ]
