# Generated by Django 3.0 on 2019-12-04 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='form',
            new_name='Content',
        ),
    ]
